services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthai_etl
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-enterprise
    container_name: healthai_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"